### ISSUE TITLE
缺少依赖包

### ISSUE THREAD

**Issue by dongmeiqi** [usdot-jpo-ode/jpo-ode#380] opened 2020-07-19 08:00 UTC
为什么没有ieee1609dot2依赖包	<dependency>
			<groupId>us.dot.its.jpo.ode</groupId>
			<artifactId>ieee1609dot2</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

**Comment by TonyEnglish** [comment] 2020-07-28 16:01
I don't speak Chinese, but using translate.google.com I find:
缺少依赖包 translates to "Missing dependencies" (issue description)
为什么没有 translates to "Why not"
依赖包 translates to "Dependent package"

Not exactly sure what this is issue is requesting, but it looks like you (dongmeiqi) are having trouble with an ieee1609dot2 dependency package being available.  Please let us know what you are doing and what you would like to see adjusted, explained or fixed.  Great to see engagement from the international community!

**Comment by dongmeiqi** [comment] 2020-08-11 02:19
I want to set up the project now, but in pom.xml, the dependency us.dot.its.jpo.ode.ieee1609dot2 is missing, so the project cannot run correctly

**Comment by TonyEnglish** [comment] 2020-08-12 20:45
I have reviewed the pom.xml for the jpo-ode (https://github.com/usdot-jpo-ode/jpo-ode/blob/master/pom.xml) and see no reverence to 1609.  Which line are you seeing problems with configuration per the readme (https://github.com/usdot-jpo-ode/jpo-ode/blob/master/README.md)?

**Comment by dongmeiqi** [comment] 2020-08-14 09:46
for this project pom.xml
(https://github.com/usdot-jpo-ode/jpo-security) ,the dependency us.dot.its.jpo.ode.ieee1609dot2 is missing,May I trouble you to solve it

**Comment by TonyEnglish** [comment] 2020-08-14 18:09
dongmeiqi, this seems to compile okay (I am not sure what steps you are taking to find a problem), the steps I used are:
1) git clone https://github.com/usdot-jpo-ode/jpo-security
2) .\build.cmd
3) these are the results I see:
PS C:\GitHub\test_jpo_security\jpo-security> .\build.cmd

C:\GitHub\test_jpo_security\jpo-security>call mvn -DskipTests clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jpo-security 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fedgov-cv-security-2016 ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ fedgov-cv-security-2016 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ fedgov-cv-security-2016 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to C:\GitHub\test_jpo_security\jpo-security\target\classes
[INFO] /C:/GitHub/test_jpo_security/jpo-security/src/main/java/gov/usdot/cv/security/crypto/AESProvider.java: C:\GitHub\test_jpo_security\jpo-security\src\main\java\gov\usdot\cv\security\crypto\AESProvider.java uses or overrides a deprecated API.
[INFO] /C:/GitHub/test_jpo_security/jpo-security/src/main/java/gov/usdot/cv/security/crypto/AESProvider.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ fedgov-cv-security-2016 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\GitHub\test_jpo_security\jpo-security\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ fedgov-cv-security-2016 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 15 source files to C:\GitHub\test_jpo_security\jpo-security\target\test-classes
[INFO] /C:/GitHub/test_jpo_security/jpo-security/src/test/java/gov/usdot/cv/security/crypto/AsymmetricKeysTest.java: C:\GitHub\test_jpo_security\jpo-security\src\test\java\gov\usdot\cv\security\crypto\AsymmetricKeysTest.java uses unchecked or unsafe operations.
[INFO] /C:/GitHub/test_jpo_security/jpo-security/src/test/java/gov/usdot/cv/security/crypto/AsymmetricKeysTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fedgov-cv-security-2016 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ fedgov-cv-security-2016 ---
[INFO] Building jar: C:\GitHub\test_jpo_security\jpo-security\target\fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ fedgov-cv-security-2016 ---
[INFO]
Loading source files for package gov.usdot.cv.security.cert...
Loading source files for package gov.usdot.cv.security.clock...
Loading source files for package gov.usdot.cv.security.crypto...
Loading source files for package gov.usdot.cv.security.msg...
Loading source files for package gov.usdot.cv.security.util...
Constructing Javadoc information...
Standard Doclet version 1.8.0_162
Building tree for all the packages and classes...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\CertificateException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\CertificateManager.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\CertificateWrapper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\FileCertificateStore.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\ClockHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\AESProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\CryptoException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\CryptoHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\CryptoProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\EcdsaP256SignatureWrapper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\ECDSAProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\ECIESProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\Ieee1609dot2Mac1.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\IEEE1609p2Message.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\MessageException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\ByteArrayHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\Ieee1609dot2Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\Time32Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\Time64Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\overview-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\package-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\package-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\package-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\package-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\package-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\package-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\package-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\package-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\package-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\package-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\package-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\package-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\package-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\package-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\package-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\constant-values.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\serialized-form.html...
Copying file StandardDocFile[file:C:\GitHub\test_jpo_security\jpo-security\src\main\resources\stylesheet.css] to file stylesheet.css...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\class-use\FileCertificateStore.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\class-use\CertificateWrapper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\class-use\CertificateManager.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\class-use\CertificateException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\class-use\ClockHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\Ieee1609dot2Mac1.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\ECIESProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\ECDSAProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\EcdsaP256SignatureWrapper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\CryptoProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\CryptoHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\CryptoException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\class-use\AESProvider.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\class-use\MessageException.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\class-use\IEEE1609p2Message.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\class-use\Time64Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\class-use\Time32Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\class-use\Ieee1609dot2Helper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\class-use\ByteArrayHelper.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\cert\package-use.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\clock\package-use.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\crypto\package-use.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\msg\package-use.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\gov\usdot\cv\security\util\package-use.html...
Building index for all the packages and classes...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\overview-tree.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\index-all.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\deprecated-list.html...
Building index for all classes...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\allclasses-frame.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\allclasses-noframe.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\index.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\overview-summary.html...
Generating C:\GitHub\test_jpo_security\jpo-security\target\apidocs\help-doc.html...
[INFO] Building jar: C:\GitHub\test_jpo_security\jpo-security\target\fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ fedgov-cv-security-2016 ---
[INFO] Installing C:\GitHub\test_jpo_security\jpo-security\target\fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar to C:\Users\tony.NEAERA\.m2\repository\gov\usdot\fedgov-cv-security-2016\1.0.0-SNAPSHOT\fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\GitHub\test_jpo_security\jpo-security\pom.xml to C:\Users\tony.NEAERA\.m2\repository\gov\usdot\fedgov-cv-security-2016\1.0.0-SNAPSHOT\fedgov-cv-security-2016-1.0.0-SNAPSHOT.pom
[INFO] Installing C:\GitHub\test_jpo_security\jpo-security\target\fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar to C:\Users\tony.NEAERA\.m2\repository\gov\usdot\fedgov-cv-security-2016\1.0.0-SNAPSHOT\fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.653 s
[INFO] Finished at: 2020-08-14T12:02:52-06:00
[INFO] Final Memory: 26M/750M
[INFO] ------------------------------------------------------------------------
Press any key to continue . . .
PS C:\GitHub\test_jpo_security\jpo-security>

**Comment by dongmeiqi** [comment] 2020-08-18 10:16
I'm missing the bottom bag：

[WARNING] The POM for us.dot.its.jpo.ode:ieee1609dot2:jar:0.0.1-SNAPSHOT is missing, no dependency information available。

Below is the error log：

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/2.10.4/maven-javadoc-plugin-2.10.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/2.10.4/maven-javadoc-plugin-2.10.4.pom (16 kB at 2.1 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/28/maven-plugins-28.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/28/maven-plugins-28.pom (0 B at 0 B/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/2.10.4/maven-javadoc-plugin-2.10.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/2.10.4/maven-javadoc-plugin-2.10.4.jar (415 kB at 12 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.0.2/maven-resources-plugin-3.0.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.0.2/maven-resources-plugin-3.0.2.pom (7.1 kB at 7.3 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/30/maven-plugins-30.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/30/maven-plugins-30.pom (0 B at 0 B/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.0.2/maven-resources-plugin-3.0.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/3.0.2/maven-resources-plugin-3.0.2.jar (32 kB at 11 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3.pom (11 kB at 9.2 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.3/maven-compiler-plugin-3.3.jar (46 kB at 15 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.pom (1.1 kB at 1.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/junit/junit/4.8.2/junit-4.8.2.pom
Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/4.8.2/junit-4.8.2.pom (1.5 kB at 2.9 kB/s)
[WARNING] The POM for us.dot.its.jpo.ode:ieee1609dot2:jar:0.0.1-SNAPSHOT is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar
Downloading from central: https://repo.maven.apache.org/maven2/junit/junit/4.8.2/junit-4.8.2.jar
Downloading from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar (0 B at 0 B/s)
Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/4.8.2/junit-4.8.2.jar (237 kB at 17 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.58/bcprov-jdk15on-1.58.jar (4.0 MB at 20 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:40 min
[INFO] Finished at: 2020-08-18T18:15:53+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fedgov-cv-security-2016: Could not resolve dependencies for project gov.usdot:fedgov-cv-security-2016:jar:1.0.0-SNAPSHOT: Could not find artifact us.dot.its.jpo.ode:ieee1609dot2:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by TonyEnglish** [comment] 2020-08-18 17:04
Please see the specific commands I listed in my last post with the response included.  Please run these commands and report the commands and response.  With this information i can help.  The log you sent does not show what you have done, it shows no commands so i am having trouble reproducing your results.

**Comment by dongmeiqi** [comment] 2020-08-19 05:14
C:\Users\dongm>cd jpo-security

C:\Users\dongm\jpo-security>build.cmd

C:\Users\dongm\jpo-security>call mvn -DskipTests clean install
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< gov.usdot:fedgov-cv-security-2016 >------------------
[INFO] Building jpo-security 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for us.dot.its.jpo.ode:ieee1609dot2:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.875 s
[INFO] Finished at: 2020-08-19T13:13:26+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fedgov-cv-security-2016: Could not resolve dependencies for project gov.usdot:fedgov-cv-security-2016:jar:1.0.0-SNAPSHOT: Could not find artifact us.dot.its.jpo.ode:ieee1609dot2:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by dongmeiqi** [comment] 2020-08-19 05:15
It is obvious that there is a lack of dependency package

**Comment by dongmeiqi** [comment] 2020-08-19 05:17
You took the Maven warehouse us.dot.its . jpo.ode : ieee1609dot2 jar package upload

**Comment by TonyEnglish** [comment] 2020-08-19 13:04
Where is your command for cloning the repo.  Maybe you have a different repo.  Also, did you execute the required:
git config --global core.autocrlf false
After you clone the repo and build, you will find a directory jpo-security\target that contains two JAR files:
fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar
fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar
These are the ones I think are missing for you.  They should be created for you when you clone the repo I linked and build the repo.
I just tested a fresh clone and build and they seem to compile error free. Your last comment is unclear to me, are you saying I am working in a different repo than you are?

**Comment by TonyEnglish** [comment] 2020-08-19 13:09
One other thing, do you have the required Java 8?  You will find the general documentation for building the solutions located here:
https://github.com/usdot-jpo-ode/jpo-ode
in the readme.md

**Comment by dongmeiqi** [comment] 2020-08-31 02:07
I told you, less jar package, you directly us.dot.its . jpo.ode : ieee1609dot2 jar package upload

**Comment by dongmeiqi** [comment] 2020-08-31 02:08
It's no use talking about it for a long time. You are too unprofessional

**Comment by TonyEnglish** [comment] 2020-08-31 15:16
[fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/5151112/fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar.txt)
[fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/5151113/fedgov-cv-security-2016-1.0.0-SNAPSHOT-javadoc.jar.txt)

**Comment by dongmeiqi** [comment] 2020-09-01 07:05
Not these two jar packages, but dependent packages。
Dependency package with artifact ID of ieee1609dot2。
as follows：
<dependency>
			<groupId>us.dot.its.jpo.ode</groupId>
			<artifactId>ieee1609dot2</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

**Comment by dan-du-car** [comment] 2020-09-02 18:09
@dongmeiqi 
The jpo-ode repository depends on sub modules: jpo-ode-common, jpo-ode-plugins, jpo-ode-core, and jpo-ode-svcs.  I think the jpo-security repository is a standalone module.  It is not actively in use, and might be deprecated in the future. If you only need to install jpo-ode, you may avoid building jpo-security by referring to this guide https://github.com/usdot-jpo-ode/jpo-ode#installation.

**Comment by TonyEnglish** [comment] 2023-02-07 22:52
Closing out due to no follow-up in past 2 years.

**Closed by TonyEnglish** 2023-02-07 22:52 UTC
